import type { Metadata } from "next";
import { Inter, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import SideBar from "@/components/sidebar";
import { GlobalProvider } from "@/contex/globalContex";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Slicing Test",
  description: "Generated by Galang Anggara",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/zsb2xla.css"/>
      </head>
      <body
        className={`${inter.variable} font-sans`}
      >
        <GlobalProvider>
          <Navbar text="Dashboard"/>
          <SideBar/>
          {children}
        </GlobalProvider>
        
      </body>
    </html>
  );
}
